services:
  bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      mongodb:
        condition: service_healthy
      lavalink:
        condition: service_started

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_PORT=2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml

volumes:
  mongodb_data:
